import json
from datetime import datetime, timedelta

products = [
    {
        "id": "fw-001",
        "slug": "black-embroidered-kurta",
        "name": "Black Embroidered Kurta",
        "category": "ready-to-wear",
        "subcategory": "Kurtas",
        "collection": "the-everyday-edit",
        "price": 8500,
        "compareAt": None,
        "badge": "Bestseller",
        "sizes": ["S", "M", "L"],
        "colors": ["Onyx"],
        "fabric": "Raw Silk",
        "availability": "in-stock",
        "bestSelling": 95,
        "date": "2025-02-01",
        "images": ["/images/ready-to-wear-editorial.png"],
        "description": "A refined black kurta with delicate white threadwork."
    },
    {
        "id": "fw-002",
        "slug": "ivory-floral-unstitched",
        "name": "Ivory Floral Unstitched",
        "category": "unstitched",
        "subcategory": "Printed Lawn",
        "collection": "rangrez",
        "price": 4500,
        "compareAt": None,
        "badge": "New in",
        "sizes": ["3-piece"],
        "colors": ["Ivory", "Crimson"],
        "fabric": "Lawn",
        "availability": "in-stock",
        "bestSelling": 80,
        "date": "2025-02-15",
        "images": ["/images/unstitched-editorial.png"],
        "description": "A classic ivory three-piece lawn with floral motifs."
    },
    {
        "id": "fw-003",
        "slug": "tan-leather-bag",
        "name": "Tan Leather Bag & Dupatta",
        "category": "accessories",
        "subcategory": "Bags",
        "collection": "gulbahar",
        "price": 12500,
        "compareAt": 14000,
        "badge": "Sale",
        "sizes": ["One size"],
        "colors": ["Tan", "Gold"],
        "fabric": "Leather",
        "availability": "low-stock",
        "bestSelling": 90,
        "date": "2025-01-10",
        "images": ["/images/accessories-editorial.png"],
        "description": "An exquisite tan leather handbag paired with an embroidered dupatta."
    },
    {
        "id": "fw-004",
        "slug": "rose-gold-occasion-dress",
        "name": "Rose Gold Occasion Dress",
        "category": "ready-to-wear",
        "subcategory": "Occasion",
        "collection": "noor",
        "price": 25000,
        "compareAt": None,
        "badge": "Limited",
        "sizes": ["M", "L"],
        "colors": ["Rose", "Gold"],
        "fabric": "Organza",
        "availability": "in-stock",
        "bestSelling": 65,
        "date": "2024-12-20",
        "images": ["/images/occasion-editorial.png"],
        "description": "A breathtaking rose gold formal dress for evening wear."
    },
    {
        "id": "fw-005",
        "slug": "luxury-courtyard-unstitched",
        "name": "Luxury Courtyard Unstitched",
        "category": "unstitched",
        "subcategory": "Embroidered",
        "collection": "rooh",
        "price": 18000,
        "compareAt": None,
        "badge": None,
        "sizes": ["3-piece"],
        "colors": ["Teal", "Silver"],
        "fabric": "Chiffon",
        "availability": "in-stock",
        "bestSelling": 88,
        "date": "2025-01-05",
        "images": ["/images/hero-luxury-courtyard.png"],
        "description": "Intricate silver embroidery on a teal chiffon canvas."
    },
    {
        "id": "fw-006",
        "slug": "heavy-gold-jhumkas",
        "name": "Heavy Gold Jhumkas & Clutch",
        "category": "accessories",
        "subcategory": "Jewellery",
        "collection": "noor",
        "price": 6500,
        "compareAt": None,
        "badge": "Bestseller",
        "sizes": ["One size"],
        "colors": ["Gold", "Ruby"],
        "fabric": "Brass",
        "availability": "in-stock",
        "bestSelling": 92,
        "date": "2025-02-10",
        "images": ["/images/luxury_accessories_gold_1790427717901.jpg"],
        "description": "Traditional gold-plated jhumkas styled with a velvet clutch."
    },
    {
        "id": "fw-007",
        "slug": "burgundy-velvet-lehenga",
        "name": "Burgundy Velvet Lehenga",
        "category": "ready-to-wear",
        "subcategory": "Dresses",
        "collection": "rooh",
        "price": 45000,
        "compareAt": 50000,
        "badge": "Sale",
        "sizes": ["S", "M"],
        "colors": ["Burgundy", "Gold"],
        "fabric": "Velvet",
        "availability": "low-stock",
        "bestSelling": 98,
        "date": "2024-11-15",
        "images": ["/images/luxury_formal_burgundy_1790427684372.jpg"],
        "description": "A majestic burgundy velvet formal outfit with heavy zari work."
    },
    {
        "id": "fw-008",
        "slug": "emerald-zari-suit",
        "name": "Emerald Zari Suit",
        "category": "ready-to-wear",
        "subcategory": "Shirts",
        "collection": "gulbahar",
        "price": 22000,
        "compareAt": None,
        "badge": "New in",
        "sizes": ["S", "M", "L"],
        "colors": ["Emerald", "Silver"],
        "fabric": "Raw Silk",
        "availability": "in-stock",
        "bestSelling": 85,
        "date": "2025-02-18",
        "images": ["/images/luxury_formal_emerald_1790427707411.jpg"],
        "description": "Deep emerald raw silk embellished with striking silver details."
    },
    {
        "id": "fw-009",
        "slug": "royal-velvet-flatlay",
        "name": "Royal Velvet Unstitched",
        "category": "unstitched",
        "subcategory": "Cambric",
        "collection": "noor",
        "price": 14500,
        "compareAt": None,
        "badge": None,
        "sizes": ["3-piece"],
        "colors": ["Navy", "Emerald"],
        "fabric": "Velvet",
        "availability": "in-stock",
        "bestSelling": 70,
        "date": "2025-01-25",
        "images": ["/images/luxury_unstitched_flatlay_1790427695988.jpg"],
        "description": "Premium unstitched velvet fabrics presented in a royal flatlay."
    }
]

with open(r'artifacts\fatima-wardrobe\src\data\products.json', 'w', encoding='utf-8') as f:
    json.dump(products, f, indent=2)

print("Generated exactly 9 unique products with no duplicate images!")
